### ISSUE TITLE
dyld error after upgrading to v0.4

### ISSUE THREAD

**Issue by jiajiawang** [ishkawa/APIKit#18]
dyld: Symbol not found: _OBJC_METACLASS_$__TtC6APIKit3API

Got this error after upgrading to v0.4 when trying to run the app on device (works fine in simulator).

And it would work if rolled back to old version.

**Comment by ishkawa** [comment]
Does this error occur on APIKit DemoApp too?

**Comment by ishkawa** [comment]
If it doesn't, you may forgot to embed APIKit into your app target.

![](http://gyazo.com/f8076403cc14d8d5e2a80ed8d5a1c53f.png)

**Comment by ishkawa** [comment]
> No news is good news.
